// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartLockService.proto

package ds.service1;

public interface LockRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartLock.LockRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 lockId = 1;</code>
   */
  int getLockId();
}
