// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartLockService.proto

package ds.service1;

public interface LockResponseeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartLock.LockResponsee)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string lockConfirmation = 1;</code>
   */
  java.lang.String getLockConfirmation();
  /**
   * <code>string lockConfirmation = 1;</code>
   */
  com.google.protobuf.ByteString
      getLockConfirmationBytes();
}
