// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartLockService.proto

package ds.service1;

public final class SmartLockServiceImpl {
  private SmartLockServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartLock_UnlockRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartLock_UnlockRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartLock_UnlockResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartLock_UnlockResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartLock_LockRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartLock_LockRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartLock_LockResponsee_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartLock_LockResponsee_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026SmartLockService.proto\022\tSmartLock\"&\n\rU" +
      "nlockRequest\022\025\n\runlockRequest\030\001 \001(\t\"\'\n\016U" +
      "nlockResponse\022\025\n\runlockAproval\030\001 \001(\t\"2\n\013" +
      "LockRequest\022\016\n\006lockId\030\001 \001(\005\022\023\n\013lockReque" +
      "st\030\002 \001(\t\")\n\rLockResponsee\022\030\n\020lockConfirm" +
      "ation\030\001 \001(\t2\236\001\n\tSmartLock\022D\n\013UnlockDoors" +
      "\022\030.SmartLock.UnlockRequest\032\031.SmartLock.U" +
      "nlockResponse\"\000\022K\n\023lockDoorsAndWindows\022\026" +
      ".SmartLock.LockRequest\032\030.SmartLock.LockR" +
      "esponsee\"\000(\001B%\n\013ds.service1B\024SmartLockSe" +
      "rviceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_SmartLock_UnlockRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SmartLock_UnlockRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartLock_UnlockRequest_descriptor,
        new java.lang.String[] { "UnlockRequest", });
    internal_static_SmartLock_UnlockResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SmartLock_UnlockResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartLock_UnlockResponse_descriptor,
        new java.lang.String[] { "UnlockAproval", });
    internal_static_SmartLock_LockRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_SmartLock_LockRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartLock_LockRequest_descriptor,
        new java.lang.String[] { "LockId", "LockRequest", });
    internal_static_SmartLock_LockResponsee_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_SmartLock_LockResponsee_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartLock_LockResponsee_descriptor,
        new java.lang.String[] { "LockConfirmation", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
