// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartLockService.proto

package ds.service1;

public interface UnlockRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartLock.UnlockRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string unlockRequest = 1;</code>
   */
  java.lang.String getUnlockRequest();
  /**
   * <code>string unlockRequest = 1;</code>
   */
  com.google.protobuf.ByteString
      getUnlockRequestBytes();
}
