// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartLockService.proto

package ds.service1;

public interface UnlockResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartLock.UnlockResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string unlockAproval = 1;</code>
   */
  java.lang.String getUnlockAproval();
  /**
   * <code>string unlockAproval = 1;</code>
   */
  com.google.protobuf.ByteString
      getUnlockAprovalBytes();
}
