// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CCTVService.proto

package ds.service3;

public final class CCTVServiceImpl {
  private CCTVServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CCTVService_ImagesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CCTVService_ImagesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CCTVService_ImagesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CCTVService_ImagesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CCTVService_PetAlertRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CCTVService_PetAlertRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CCTVService_PetAlertResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CCTVService_PetAlertResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021CCTVService.proto\022\013CCTVService\"&\n\rImag" +
      "esRequest\022\025\n\rRequestImages\030\001 \001(\t\"(\n\016Imag" +
      "esResponse\022\026\n\016ResponseImages\030\001 \001(\t\"#\n\017Pe" +
      "tAlertRequest\022\020\n\010petAlert\030\001 \001(\t\"%\n\020PetAl" +
      "ertResponse\022\021\n\tAlarmsOff\030\001 \001(\t2\251\001\n\013CCTVS" +
      "ervice\022O\n\016CamerasViewing\022\032.CCTVService.I" +
      "magesRequest\032\033.CCTVService.ImagesRespons" +
      "e\"\000(\0010\001\022I\n\010PetAlert\022\034.CCTVService.PetAle" +
      "rtRequest\032\035.CCTVService.PetAlertResponse" +
      "\"\000B \n\013ds.service3B\017CCTVServiceImplP\001b\006pr" +
      "oto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_CCTVService_ImagesRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CCTVService_ImagesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CCTVService_ImagesRequest_descriptor,
        new java.lang.String[] { "RequestImages", });
    internal_static_CCTVService_ImagesResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_CCTVService_ImagesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CCTVService_ImagesResponse_descriptor,
        new java.lang.String[] { "ResponseImages", });
    internal_static_CCTVService_PetAlertRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_CCTVService_PetAlertRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CCTVService_PetAlertRequest_descriptor,
        new java.lang.String[] { "PetAlert", });
    internal_static_CCTVService_PetAlertResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_CCTVService_PetAlertResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CCTVService_PetAlertResponse_descriptor,
        new java.lang.String[] { "AlarmsOff", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
