// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CCTVService.proto

package ds.service3;

public final class CCTVServiceImpl {
  private CCTVServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CCTVService_ImagesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CCTVService_ImagesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CCTVService_ImagesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CCTVService_ImagesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CCTVService_PetAlertRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CCTVService_PetAlertRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CCTVService_PetAlertResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CCTVService_PetAlertResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021CCTVService.proto\022\013CCTVService\"0\n\rImag" +
      "esRequest\022\020\n\010cameraID\030\001 \001(\005\022\r\n\005image\030\002 \001" +
      "(\t\"1\n\016ImagesResponse\022\020\n\010cameraID\030\001 \001(\005\022\r" +
      "\n\005image\030\002 \001(\t\"#\n\017PetAlertRequest\022\020\n\010petA" +
      "lert\030\001 \001(\t\"%\n\020PetAlertResponse\022\021\n\tAlarms" +
      "Off\030\001 \001(\t2\251\001\n\013CCTVService\022O\n\016CamerasView" +
      "ing\022\032.CCTVService.ImagesRequest\032\033.CCTVSe" +
      "rvice.ImagesResponse\"\000(\0010\001\022I\n\010PetAlert\022\034" +
      ".CCTVService.PetAlertRequest\032\035.CCTVServi" +
      "ce.PetAlertResponse\"\000B \n\013ds.service3B\017CC" +
      "TVServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_CCTVService_ImagesRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CCTVService_ImagesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CCTVService_ImagesRequest_descriptor,
        new java.lang.String[] { "CameraID", "Image", });
    internal_static_CCTVService_ImagesResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_CCTVService_ImagesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CCTVService_ImagesResponse_descriptor,
        new java.lang.String[] { "CameraID", "Image", });
    internal_static_CCTVService_PetAlertRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_CCTVService_PetAlertRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CCTVService_PetAlertRequest_descriptor,
        new java.lang.String[] { "PetAlert", });
    internal_static_CCTVService_PetAlertResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_CCTVService_PetAlertResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CCTVService_PetAlertResponse_descriptor,
        new java.lang.String[] { "AlarmsOff", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
