// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CCTVService.proto

package ds.service3;

public interface ImagesResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CCTVService.ImagesResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string ResponseImages = 1;</code>
   */
  java.lang.String getResponseImages();
  /**
   * <code>string ResponseImages = 1;</code>
   */
  com.google.protobuf.ByteString
      getResponseImagesBytes();
}
