// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CCTVService.proto

package ds.service3;

public interface ImagesRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CCTVService.ImagesRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string RequestImages = 1;</code>
   */
  java.lang.String getRequestImages();
  /**
   * <code>string RequestImages = 1;</code>
   */
  com.google.protobuf.ByteString
      getRequestImagesBytes();
}
