// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CCTVService.proto

package ds.service3;

public interface ImagesResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CCTVService.ImagesResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 cameraID = 1;</code>
   */
  int getCameraID();

  /**
   * <code>string image = 2;</code>
   */
  java.lang.String getImage();
  /**
   * <code>string image = 2;</code>
   */
  com.google.protobuf.ByteString
      getImageBytes();
}
