// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CCTVService.proto

package ds.service3;

public interface PetAlertResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CCTVService.PetAlertResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string AlarmsOff = 1;</code>
   */
  java.lang.String getAlarmsOff();
  /**
   * <code>string AlarmsOff = 1;</code>
   */
  com.google.protobuf.ByteString
      getAlarmsOffBytes();
}
