// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CCTVService.proto

package ds.service3;

public interface PetAlertRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CCTVService.PetAlertRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string petAlert = 1;</code>
   */
  java.lang.String getPetAlert();
  /**
   * <code>string petAlert = 1;</code>
   */
  com.google.protobuf.ByteString
      getPetAlertBytes();
}
