// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IntruderAlarmService.proto

package ds.service2;

public interface AlertResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:IntruderAlarm.AlertResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string sentHelp = 1;</code>
   */
  java.lang.String getSentHelp();
  /**
   * <code>string sentHelp = 1;</code>
   */
  com.google.protobuf.ByteString
      getSentHelpBytes();
}
