// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IntruderAlarmService.proto

package ds.service2;

public interface AlertRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:IntruderAlarm.AlertRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool intruder = 1;</code>
   */
  boolean getIntruder();
}
