// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IntruderAlarmService.proto

package ds.service2;

public final class IntruderAlarmServiceImpl {
  private IntruderAlarmServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_IntruderAlarm_AlertRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_IntruderAlarm_AlertRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_IntruderAlarm_AlertResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_IntruderAlarm_AlertResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_IntruderAlarm_LightRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_IntruderAlarm_LightRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_IntruderAlarm_LightResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_IntruderAlarm_LightResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032IntruderAlarmService.proto\022\rIntruderAl" +
      "arm\" \n\014AlertRequest\022\020\n\010intruder\030\001 \001(\010\"!\n" +
      "\rAlertResponse\022\020\n\010sentHelp\030\001 \001(\t\"$\n\014Ligh" +
      "tRequest\022\024\n\014lightTrigger\030\001 \001(\010\"!\n\rLightR" +
      "esponse\022\020\n\010lightsOn\030\002 \001(\t2\254\001\n\rIntruderAl" +
      "arm\022L\n\rIntruderAlert\022\033.IntruderAlarm.Ale" +
      "rtRequest\032\034.IntruderAlarm.AlertResponse\"" +
      "\000\022M\n\014LightOnAlert\022\033.IntruderAlarm.LightR" +
      "equest\032\034.IntruderAlarm.LightResponse\"\0000\001" +
      "B)\n\013ds.service2B\030IntruderAlarmServiceImp" +
      "lP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_IntruderAlarm_AlertRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_IntruderAlarm_AlertRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_IntruderAlarm_AlertRequest_descriptor,
        new java.lang.String[] { "Intruder", });
    internal_static_IntruderAlarm_AlertResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_IntruderAlarm_AlertResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_IntruderAlarm_AlertResponse_descriptor,
        new java.lang.String[] { "SentHelp", });
    internal_static_IntruderAlarm_LightRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_IntruderAlarm_LightRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_IntruderAlarm_LightRequest_descriptor,
        new java.lang.String[] { "LightTrigger", });
    internal_static_IntruderAlarm_LightResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_IntruderAlarm_LightResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_IntruderAlarm_LightResponse_descriptor,
        new java.lang.String[] { "LightsOn", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
