// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IntruderAlarmService.proto

package ds.service2;

public interface LightResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:IntruderAlarm.LightResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string lightsOn = 2;</code>
   */
  java.lang.String getLightsOn();
  /**
   * <code>string lightsOn = 2;</code>
   */
  com.google.protobuf.ByteString
      getLightsOnBytes();
}
