// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IntruderAlarmService.proto

package ds.service2;

public interface LightResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:IntruderAlarm.LightResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 lightId = 1;</code>
   */
  int getLightId();

  /**
   * <code>bool lightsOn = 2;</code>
   */
  boolean getLightsOn();
}
