// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IntruderAlarmService.proto

package ds.service2;

public interface LightRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:IntruderAlarm.LightRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string lightTrigger = 1;</code>
   */
  java.lang.String getLightTrigger();
  /**
   * <code>string lightTrigger = 1;</code>
   */
  com.google.protobuf.ByteString
      getLightTriggerBytes();
}
