// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IntruderAlarmService.proto

package ds.service2;

public interface LightRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:IntruderAlarm.LightRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool lightTrigger = 1;</code>
   */
  boolean getLightTrigger();
}
